language: node_js
node_js:
  - "node"
cache: yarn
script:
  - yarn test --coverage
  before_install:
    - npm i -g graphql
after_success: 
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
